"""empty message

Revision ID: 260dd56efb9a
Revises: a16f69a1cfdd
Create Date: 2016-05-03 03:20:01.205581

"""

# revision identifiers, used by Alembic.
revision = '260dd56efb9a'
down_revision = 'a16f69a1cfdd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('guess_by_team_id', 'guess', ['team_id'], unique=False)
    op.create_table('guess_tuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guess_id', sa.Integer(), nullable=True),
    sa.Column('tuser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guess_id'], ['guess.id'], ),
    sa.ForeignKeyConstraint(['tuser_id'], ['tuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('guess_tuser_by_guess_id', 'guess_tuser', ['guess_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('guess_tuser_by_guess_id', table_name='guess_tuser')
    op.drop_table('guess_tuser')
    op.drop_index('guess_by_team_id', table_name='guess')
    op.drop_table('guess')
    op.drop_table('team')
    ### end Alembic commands ###
