"""empty message

Revision ID: 32375554114b
Revises: 4b0e812d4942
Create Date: 2016-02-11 04:36:06.343071

"""

# revision identifiers, used by Alembic.
revision = '32375554114b'
down_revision = '4b0e812d4942'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('tweet_by_timestamp', 'tweet', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tweet_by_timestamp', table_name='tweet')
    ### end Alembic commands ###
