"""empty message

Revision ID: 3af6c5dc4ac
Revises: 32375554114b
Create Date: 2016-03-02 21:39:02.608635

"""

# revision identifiers, used by Alembic.
revision = '3af6c5dc4ac'
down_revision = '32375554114b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tuser_tuser', sa.Column('timestamp', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tuser_tuser', 'timestamp')
    ### end Alembic commands ###
