"""Add team and team_tuser guess tables.

Revision ID: 5e540809e9e1
Revises: a16f69a1cfdd
Create Date: 2016-05-03 03:24:51.092880

"""

# revision identifiers, used by Alembic.
revision = '5e540809e9e1'
down_revision = 'a16f69a1cfdd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_tuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('tuser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['tuser_id'], ['tuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('team_tuser_by_team_id', 'team_tuser', ['team_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('team_tuser_by_team_id', table_name='team_tuser')
    op.drop_table('team_tuser')
    op.drop_table('team')
    ### end Alembic commands ###
