"""empty message

Revision ID: 7ecb89c09c14
Revises: 687f6d810c83
Create Date: 2016-07-01 07:15:40.245638

"""

# revision identifiers, used by Alembic.
revision = '7ecb89c09c14'
down_revision = '687f6d810c83'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('user', sa.LargeBinary(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweet', 'user')
    ### end Alembic commands ###
