"""Add per-user educational material table

Revision ID: 8a3ad7a5b53
Revises: 8d6b64a8712
Create Date: 2015-12-29 16:11:49.472180

"""

# revision identifiers, used by Alembic.
revision = '8a3ad7a5b53'
down_revision = '8d6b64a8712'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tuser_lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tuser_id', sa.BigInteger(), nullable=True),
    sa.Column('pointer_type', sa.String(length=32), nullable=True),
    sa.Column('pointer_id', sa.Text(), nullable=True),
    sa.Column('message_title', sa.Text(), nullable=True),
    sa.Column('message_body', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tuser_id'], ['tuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('tuserlesson_by_tuser_id', 'tuser_lesson', ['tuser_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tuserlesson_by_tuser_id', table_name='tuser_lesson')
    op.drop_table('tuser_lesson')
    ### end Alembic commands ###
