"""empty message

Revision ID: 9d31846158ff
Revises: c19c5eb32462
Create Date: 2016-06-29 04:42:21.292325

"""

# revision identifiers, used by Alembic.
revision = '9d31846158ff'
down_revision = 'c19c5eb32462'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('tweetentity_by_type_text', 'tweet_entity', ['type', 'text'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tweetentity_by_type_text', table_name='tweet_entity')
    ### end Alembic commands ###
