"""empty message

Revision ID: b69838df1800
Revises: 9d31846158ff
Create Date: 2016-06-29 05:19:56.105851

"""

# revision identifiers, used by Alembic.
revision = 'b69838df1800'
down_revision = '9d31846158ff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('tweetentity_by_type_text_tweet_id', 'tweet_entity', ['type', 'text', 'tweet_id'], unique=False)
    op.drop_index('tweetentity_by_type_text', table_name='tweet_entity')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('tweetentity_by_type_text', 'tweet_entity', ['type', 'text'], unique=False)
    op.drop_index('tweetentity_by_type_text_tweet_id', table_name='tweet_entity')
    ### end Alembic commands ###
