"""Fix team.team_id unnecessary foreign key team.id

Revision ID: c19c5eb32462
Revises: 5e540809e9e1
Create Date: 2016-05-03 03:32:33.686299

"""

# revision identifiers, used by Alembic.
revision = 'c19c5eb32462'
down_revision = '5e540809e9e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'team_team_id_fkey', 'team', type_='foreignkey')
    op.drop_column('team', 'team_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'team_team_id_fkey', 'team', 'team', ['team_id'], ['id'])
    ### end Alembic commands ###
