"""Add more indices on tuser and tweet

Revision ID: e58250f062a5
Revises: 48b1999900ab
Create Date: 2016-06-29 11:43:45.527144

"""

# revision identifiers, used by Alembic.
revision = 'e58250f062a5'
down_revision = '48b1999900ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('tuser_by_screen_name', 'tuser', ['screen_name'], unique=False)
    op.create_index('tweet_by_user_id_by_id_by_time', 'tweet', ['user_id', 'tweet_id', 'timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tweet_by_user_id_by_id_by_time', table_name='tweet')
    op.drop_index('tuser_by_screen_name', table_name='tuser')
    ### end Alembic commands ###
