"""empty message

Revision ID: 23c935e557ac
Revises: None
Create Date: 2015-11-11 02:00:07.640331

"""

# revision identifiers, used by Alembic.
revision = '23c935e557ac'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'team_bot', 'tuser', ['twitter_id'], ['user_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_bot', type_='foreignkey')
    ### end Alembic commands ###
