"""empty message

Revision ID: 431defc6f54f
Revises: None
Create Date: 2015-11-11 02:15:16.311663

"""

# revision identifiers, used by Alembic.
revision = '431defc6f54f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_bot',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('twitter_id', sa.String(length=32), nullable=False),
    sa.Column('screen_name', sa.String(length=32), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('kill_date', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('team_id', 'twitter_id')
    )
    op.create_index('by_tuser_id', 'team_bot', ['twitter_id'], unique=False)
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('screen_name', sa.String(length=32), nullable=True),
    sa.Column('full_name', sa.String(length=32), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.Column('total_tweets', sa.Integer(), nullable=True),
    sa.Column('interesting', sa.Boolean(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('profile_image_url', sa.Text(), nullable=True),
    sa.Column('profile_banner_url', sa.Text(), nullable=True),
    sa.Column('protected', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('tuser_by_id_timestamp', 'tuser', ['user_id', 'timestamp'], unique=False)
    op.create_table('tweet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('interesting', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('tweet_by_tweet_id', 'tweet', ['tweet_id'], unique=False)
    op.create_index('tweet_by_user_id_by_time', 'tweet', ['user_id', 'timestamp'], unique=False)
    op.create_table('test_guess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('tuser_id', sa.Integer(), nullable=True),
    sa.Column('guess_is_bot', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.ForeignKeyConstraint(['tuser_id'], ['tuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_selection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('tuser_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.ForeignKeyConstraint(['tuser_id'], ['tuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_selection')
    op.drop_table('test_guess')
    op.drop_index('tweet_by_user_id_by_time', table_name='tweet')
    op.drop_index('tweet_by_tweet_id', table_name='tweet')
    op.drop_table('tweet')
    op.drop_index('tuser_by_id_timestamp', table_name='tuser')
    op.drop_table('tuser')
    op.drop_table('test')
    op.drop_index('by_tuser_id', table_name='team_bot')
    op.drop_table('team_bot')
    ### end Alembic commands ###
